let SnowmanCanvas = document.querySelector(".Snowman");
let ctx = SnowmanCanvas.getContext("2d");

//Draw Horizon
ctx.beginPath();
ctx.fillStyle = "black";
ctx.fillRect(0, SnowmanCanvas.height/2, SnowmanCanvas.width, 5);
ctx.closePath();
ctx.beginPath();
ctx.fillStyle = "grey";
ctx.arc(SnowmanCanvas.width/2, 260, 59, 0, 2*Math.PI);
ctx.fill();
ctx.closePath();
ctx.beginPath();
ctx.fillStyle = "grey";
ctx.arc(SnowmanCanvas.width/2, 180, 40, 0, 2*Math.PI);
ctx.fill();
ctx.closePath();
ctx.beginPath();
ctx.fillStyle = "grey";
ctx.arc(SnowmanCanvas.width/2, 130, 29, 0, 2*Math.PI);
ctx.fill();
ctx.closePath();
ctx.beginPath();
ctx.fillStyle = "black";
ctx.arc(SnowmanCanvas.width/2 + 9, 120, 7, 0, 2*Math.PI);
ctx.fill();
ctx.closePath();
ctx.beginPath();
ctx.fillStyle = "black";
ctx.arc(SnowmanCanvas.width/2 - 9, 120, 7, 0, 2*Math.PI);
ctx.fill();
ctx.closePath();
ctx.beginPath();
ctx.fillStyle = "blue";
ctx.arc(SnowmanCanvas.width/2, 180, 7, 0, 2*Math.PI);
ctx.fill();
ctx.closePath();
ctx.beginPath();
ctx.fillStyle = "red";
ctx.arc(SnowmanCanvas.width/2, 130, 7, 0, 2*Math.PI);
ctx.fill();
ctx.closePath();
ctx.beginPath();
ctx.fillStyle = "blue";
ctx.arc(SnowmanCanvas.width/2, 260, 7, 0, 2*Math.PI);
ctx.fill();
ctx.closePath();
ctx.beginPath();
ctx.fillStyle = "blue";
ctx.arc(SnowmanCanvas.width/2, 220, 7, 0, 2*Math.PI);
ctx.fill();
ctx.closePath();